//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTesis.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Estudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Estudiante()
        {
            this.HistorialProgresion = new HashSet<HistorialProgresion>();
            this.InformeCabecera = new HashSet<InformeCabecera>();
        }
    
        public int EstudianteId { get; set; }
        public int ProfesorId { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public string Cedula { get; set; }
        public string Carrera { get; set; }
        public string TituloTesis { get; set; }
        public string NumeroResolucion { get; set; }
        public System.DateTime FechaResolucion { get; set; }
        public byte[] ArchivoResolucion { get; set; }
        public string Estado { get; set; }
        public Nullable<int> PorcentajeAvance { get; set; }
        public Nullable<System.DateTime> FechaRegistro { get; set; }
    
        public virtual Profesor Profesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialProgresion> HistorialProgresion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformeCabecera> InformeCabecera { get; set; }
    }
}
