//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTesis.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistorialProgresion
    {
        public int HistorialId { get; set; }
        public int EstudianteId { get; set; }
        public int InformeCabeceraId { get; set; }
        public System.DateTime FechaInforme { get; set; }
        public int PorcentajeEnInforme { get; set; }
        public string EstadoEnInforme { get; set; }
        public string ResumenActividades { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        public virtual InformeCabecera InformeCabecera { get; set; }
    }
}
