//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTesis.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeDetalle
    {
        public int InformeDetalleId { get; set; }
        public int InformeCabeceraId { get; set; }
        public int NumeroActividad { get; set; }
        public string DescripcionActividad { get; set; }
        public int PorcentajeActividad { get; set; }
        public string Observacion { get; set; }
    
        public virtual InformeCabecera InformeCabecera { get; set; }
    }
}
