//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTesis.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class InformeCabecera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InformeCabecera()
        {
            this.HistorialProgresion = new HashSet<HistorialProgresion>();
            this.InformeDetalle = new HashSet<InformeDetalle>();
        }
    
        public int InformeCabeceraId { get; set; }
        public int EstudianteId { get; set; }
        public int ProfesorId { get; set; }
        public string NumeroInforme { get; set; }
        public System.DateTime FechaEmision { get; set; }
        public int PorcentajeAcumulado { get; set; }
        public string Observaciones { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> EsFinal { get; set; }
    
        public virtual Estudiante Estudiante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistorialProgresion> HistorialProgresion { get; set; }
        public virtual Profesor Profesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InformeDetalle> InformeDetalle { get; set; }
    }
}
