//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTesis.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SistemaTesisEntities : DbContext
    {
        public SistemaTesisEntities()
            : base("name=SistemaTesisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Estudiante> Estudiante { get; set; }
        public virtual DbSet<HistorialProgresion> HistorialProgresion { get; set; }
        public virtual DbSet<InformeCabecera> InformeCabecera { get; set; }
        public virtual DbSet<InformeDetalle> InformeDetalle { get; set; }
        public virtual DbSet<Profesor> Profesor { get; set; }
    }
}
