//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prestamos
    {
        public int PrestamoID { get; set; }
        public Nullable<int> LibroID { get; set; }
        public Nullable<int> EstudianteID { get; set; }
        public System.DateTime FechaPrestamo { get; set; }
        public Nullable<System.DateTime> FechaDevolucionEsperada { get; set; }
        public Nullable<System.DateTime> FechaDevolucionReal { get; set; }
        public string Estado { get; set; }
        public Nullable<int> DiasRetraso { get; set; }
        public Nullable<decimal> MontoMulta { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual Libros Libros { get; set; }
    }
}
